"""Decision policy + confidence calibration fit on public train.
Generated by tools/fit_calibration.py — do not edit by hand."""

POLICY = {
 "no_arrival": "DENIED",
 "no_sponsor": "APPROVED"
}

GLOBAL_ACC = 0.787

RULE_ACC = {
 "clean": 0.673,
 "disq_flag": 0.99,
 "embargo_world": 0.99,
 "fee_missing": 0.39,
 "fee_unknown": 0.964,
 "no_arrival": 0.421,
 "no_sponsor": 0.545,
 "note_ocr": 0.99,
 "note_text": 0.99,
 "review_flag": 0.842,
 "revoked_sponsor": 0.939,
 "stale_date": 0.905,
 "transit": 0.968,
 "unpaid": 0.906,
 "wolf_embargo": 0.875
}

BUCKET_ACC = {
 "clean|hi|0": 0.723,
 "clean|hi|1": 0.699,
 "clean|lo|0": 0.654,
 "clean|mid|0": 0.625,
 "clean|mid|1": 0.672,
 "clean|text|0": 0.661,
 "disq_flag|hi|0": 0.99,
 "disq_flag|hi|1": 0.99,
 "disq_flag|hi|2+": 0.99,
 "disq_flag|lo|0": 0.99,
 "disq_flag|lo|1": 0.99,
 "disq_flag|mid|0": 0.99,
 "disq_flag|mid|1": 0.99,
 "disq_flag|mid|2+": 0.99,
 "embargo_world|hi|0": 0.99,
 "embargo_world|hi|1": 0.99,
 "embargo_world|hi|2+": 0.99,
 "embargo_world|lo|0": 0.99,
 "embargo_world|lo|1": 0.99,
 "embargo_world|mid|0": 0.99,
 "embargo_world|mid|1": 0.99,
 "embargo_world|mid|2+": 0.99,
 "embargo_world|text|0": 0.99,
 "fee_missing|hi|1": 0.375,
 "fee_missing|hi|2+": 0.406,
 "fee_missing|lo|1": 0.504,
 "fee_missing|lo|2+": 0.294,
 "fee_missing|mid|1": 0.394,
 "fee_missing|mid|2+": 0.395,
 "fee_unknown|hi|0": 0.98,
 "fee_unknown|hi|1": 0.974,
 "fee_unknown|hi|2+": 0.971,
 "fee_unknown|mid|0": 0.978,
 "fee_unknown|mid|1": 0.968,
 "fee_unknown|mid|2+": 0.893,
 "fee_unknown|text|0": 0.981,
 "no_arrival|hi|1": 0.306,
 "no_arrival|hi|2+": 0.485,
 "no_arrival|lo|2+": 0.425,
 "no_arrival|mid|1": 0.531,
 "no_arrival|mid|2+": 0.364,
 "no_sponsor|hi|1": 0.636,
 "no_sponsor|hi|2+": 0.636,
 "no_sponsor|lo|2+": 0.436,
 "no_sponsor|mid|2+": 0.49,
 "note_ocr|hi|0": 0.99,
 "note_ocr|hi|1": 0.99,
 "note_ocr|hi|2+": 0.99,
 "note_ocr|lo|0": 0.99,
 "note_ocr|lo|1": 0.99,
 "note_ocr|lo|2+": 0.99,
 "note_ocr|mid|0": 0.99,
 "note_ocr|mid|1": 0.99,
 "note_ocr|mid|2+": 0.99,
 "note_text|hi|0": 0.99,
 "note_text|hi|1": 0.99,
 "note_text|hi|2+": 0.99,
 "note_text|lo|0": 0.99,
 "note_text|lo|1": 0.99,
 "note_text|lo|2+": 0.99,
 "note_text|mid|0": 0.99,
 "note_text|mid|1": 0.99,
 "note_text|mid|2+": 0.99,
 "review_flag|hi|0": 0.845,
 "review_flag|hi|1": 0.749,
 "review_flag|lo|0": 0.885,
 "review_flag|lo|1": 0.86,
 "review_flag|mid|0": 0.859,
 "review_flag|mid|1": 0.811,
 "review_flag|mid|2+": 0.749,
 "review_flag|text|0": 0.916,
 "revoked_sponsor|hi|0": 0.976,
 "revoked_sponsor|hi|1": 0.955,
 "revoked_sponsor|hi|2+": 0.834,
 "revoked_sponsor|lo|0": 0.955,
 "revoked_sponsor|lo|1": 0.774,
 "revoked_sponsor|lo|2+": 0.946,
 "revoked_sponsor|mid|0": 0.946,
 "revoked_sponsor|mid|1": 0.969,
 "revoked_sponsor|mid|2+": 0.959,
 "revoked_sponsor|text|0": 0.977,
 "stale_date|hi|0": 0.864,
 "stale_date|hi|1": 0.937,
 "stale_date|mid|0": 0.915,
 "stale_date|mid|1": 0.853,
 "stale_date|mid|2+": 0.915,
 "stale_date|text|0": 0.946,
 "transit|hi|0": 0.98,
 "transit|hi|1": 0.895,
 "transit|hi|2+": 0.971,
 "transit|lo|1": 0.974,
 "transit|lo|2+": 0.971,
 "transit|mid|0": 0.984,
 "transit|mid|1": 0.978,
 "transit|text|0": 0.982,
 "unpaid|hi|0": 0.967,
 "unpaid|lo|0": 0.841,
 "unpaid|lo|1": 0.825,
 "unpaid|lo|2+": 0.806,
 "unpaid|mid|0": 0.946,
 "unpaid|mid|1": 0.917,
 "unpaid|text|0": 0.938,
 "wolf_embargo|hi|0": 0.889,
 "wolf_embargo|hi|1": 0.9,
 "wolf_embargo|hi|2+": 0.8,
 "wolf_embargo|lo|1": 0.889,
 "wolf_embargo|lo|2+": 0.778,
 "wolf_embargo|mid|0": 0.889,
 "wolf_embargo|mid|1": 0.909,
 "wolf_embargo|mid|2+": 0.923
}



def _band_ocr(min_conf):
    if min_conf is None:
        return "text"
    if min_conf >= 60:
        return "hi"
    if min_conf >= 45:
        return "mid"
    return "lo"


def lookup(features):
    rule = features.get("rule", "?")
    ocr = _band_ocr(features.get("min_ocr_conf"))
    miss = features.get("missing_fields", 0)
    miss = "0" if miss == 0 else ("1" if miss == 1 else "2+")
    key = f"{rule}|{ocr}|{miss}"
    if key in BUCKET_ACC:
        return BUCKET_ACC[key]
    if rule in RULE_ACC:
        return RULE_ACC[rule]
    return GLOBAL_ACC
