"""Decision policy + confidence calibration fit on public train.
Generated by tools/fit_calibration.py — do not edit by hand."""

POLICY = {
 "no_arrival": "DENIED",
 "no_sponsor": "APPROVED"
}

GLOBAL_ACC = 0.776

RULE_ACC = {
 "clean": 0.632,
 "disq_flag": 0.99,
 "embargo_world": 0.99,
 "fee_missing": 0.392,
 "fee_unknown": 0.964,
 "no_arrival": 0.417,
 "no_sponsor": 0.636,
 "note_ocr": 0.99,
 "note_text": 0.99,
 "review_flag": 0.955,
 "revoked_sponsor": 0.941,
 "stale_date": 0.905,
 "transit": 0.969,
 "unpaid": 0.909,
 "wolf_embargo": 0.875
}

BUCKET_ACC = {
 "clean|hi|0": 0.678,
 "clean|hi|1": 0.732,
 "clean|lo|0": 0.611,
 "clean|mid|0": 0.544,
 "clean|mid|1": 0.732,
 "clean|text|0": 0.619,
 "disq_flag|hi|0": 0.99,
 "disq_flag|hi|1": 0.99,
 "disq_flag|hi|2+": 0.99,
 "disq_flag|lo|0": 0.99,
 "disq_flag|lo|1": 0.99,
 "disq_flag|mid|0": 0.99,
 "disq_flag|mid|1": 0.99,
 "disq_flag|mid|2+": 0.99,
 "embargo_world|hi|0": 0.99,
 "embargo_world|hi|1": 0.99,
 "embargo_world|lo|0": 0.99,
 "embargo_world|mid|0": 0.99,
 "embargo_world|mid|1": 0.99,
 "embargo_world|mid|2+": 0.99,
 "embargo_world|text|0": 0.99,
 "fee_missing|hi|1": 0.364,
 "fee_missing|hi|2+": 0.435,
 "fee_missing|lo|1": 0.487,
 "fee_missing|lo|2+": 0.327,
 "fee_missing|mid|1": 0.365,
 "fee_missing|mid|2+": 0.414,
 "fee_unknown|hi|0": 0.98,
 "fee_unknown|hi|1": 0.976,
 "fee_unknown|hi|2+": 0.968,
 "fee_unknown|mid|0": 0.976,
 "fee_unknown|mid|1": 0.971,
 "fee_unknown|mid|2+": 0.893,
 "fee_unknown|text|0": 0.981,
 "no_arrival|hi|1": 0.256,
 "no_arrival|hi|2+": 0.481,
 "no_arrival|lo|2+": 0.458,
 "no_arrival|mid|1": 0.528,
 "no_arrival|mid|2+": 0.381,
 "no_sponsor|hi|1": 0.736,
 "no_sponsor|hi|2+": 0.709,
 "no_sponsor|lo|2+": 0.566,
 "no_sponsor|mid|2+": 0.545,
 "note_ocr|hi|0": 0.99,
 "note_ocr|hi|1": 0.99,
 "note_ocr|hi|2+": 0.99,
 "note_ocr|lo|0": 0.99,
 "note_ocr|lo|1": 0.99,
 "note_ocr|lo|2+": 0.99,
 "note_ocr|mid|0": 0.99,
 "note_ocr|mid|1": 0.99,
 "note_ocr|mid|2+": 0.99,
 "note_text|hi|0": 0.99,
 "note_text|hi|1": 0.99,
 "note_text|hi|2+": 0.99,
 "note_text|lo|0": 0.99,
 "note_text|lo|1": 0.99,
 "note_text|lo|2+": 0.99,
 "note_text|mid|0": 0.99,
 "note_text|mid|1": 0.99,
 "note_text|mid|2+": 0.99,
 "review_flag|hi|0": 0.928,
 "review_flag|lo|0": 0.964,
 "review_flag|lo|1": 0.96,
 "review_flag|mid|0": 0.972,
 "review_flag|mid|1": 0.967,
 "revoked_sponsor|hi|0": 0.976,
 "revoked_sponsor|hi|1": 0.961,
 "revoked_sponsor|hi|2+": 0.837,
 "revoked_sponsor|lo|0": 0.957,
 "revoked_sponsor|lo|1": 0.775,
 "revoked_sponsor|lo|2+": 0.948,
 "revoked_sponsor|mid|0": 0.948,
 "revoked_sponsor|mid|1": 0.972,
 "revoked_sponsor|mid|2+": 0.961,
 "revoked_sponsor|text|0": 0.978,
 "stale_date|hi|0": 0.864,
 "stale_date|hi|1": 0.937,
 "stale_date|mid|0": 0.915,
 "stale_date|mid|1": 0.853,
 "stale_date|mid|2+": 0.915,
 "stale_date|text|0": 0.946,
 "transit|hi|0": 0.981,
 "transit|hi|1": 0.904,
 "transit|hi|2+": 0.972,
 "transit|lo|1": 0.975,
 "transit|lo|2+": 0.972,
 "transit|mid|0": 0.983,
 "transit|mid|1": 0.981,
 "transit|text|0": 0.982,
 "unpaid|hi|0": 0.967,
 "unpaid|hi|2+": 0.919,
 "unpaid|lo|0": 0.843,
 "unpaid|lo|1": 0.843,
 "unpaid|lo|2+": 0.808,
 "unpaid|mid|0": 0.944,
 "unpaid|mid|1": 0.927,
 "unpaid|text|0": 0.939,
 "wolf_embargo|hi|0": 0.889,
 "wolf_embargo|hi|1": 0.9,
 "wolf_embargo|hi|2+": 0.8,
 "wolf_embargo|lo|1": 0.889,
 "wolf_embargo|lo|2+": 0.778,
 "wolf_embargo|mid|0": 0.889,
 "wolf_embargo|mid|1": 0.9,
 "wolf_embargo|mid|2+": 0.929
}



def _band_ocr(min_conf):
    if min_conf is None:
        return "text"
    if min_conf >= 60:
        return "hi"
    if min_conf >= 45:
        return "mid"
    return "lo"


def lookup(features):
    rule = features.get("rule", "?")
    ocr = _band_ocr(features.get("min_ocr_conf"))
    miss = features.get("missing_fields", 0)
    miss = "0" if miss == 0 else ("1" if miss == 1 else "2+")
    key = f"{rule}|{ocr}|{miss}"
    if key in BUCKET_ACC:
        return BUCKET_ACC[key]
    if rule in RULE_ACC:
        return RULE_ACC[rule]
    return GLOBAL_ACC
