"""Fit the confidence-calibration table from a train run.

Usage:
  MIB_FEATURES_PATH=/tmp/mib-dev/features.jsonl  (during solution.main run)
  python tools/fit_calibration.py \
      --features /tmp/mib-dev/features.jsonl \
      --predictions /tmp/mib-dev/predictions.jsonl \
      --truth <challenge>/data/train_labels.csv \
      --out solution/calib.py

Buckets each case by (rule, ocr-quality band, missing-field band), computes
the empirical adjudication accuracy per bucket with Laplace smoothing toward
the rule-level rate, and emits a lookup module. Brier-optimal confidence is
exactly the bucket's expected accuracy.
"""

import argparse
import collections
import csv
import json


def band_ocr(min_conf):
    if min_conf is None:
        return "text"
    if min_conf >= 60:
        return "hi"
    if min_conf >= 45:
        return "mid"
    return "lo"


def band_missing(n):
    return "0" if n == 0 else ("1" if n == 1 else "2+")


def bucket_of(f):
    return (f["rule"], band_ocr(f.get("min_ocr_conf")), band_missing(f.get("missing_fields", 0)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--features", required=True)
    ap.add_argument("--predictions", required=True)
    ap.add_argument("--truth", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    truth = {r["case_id"]: r["adjudication"].strip().upper() for r in csv.DictReader(open(args.truth))}
    preds = {}
    for line in open(args.predictions):
        r = json.loads(line)
        preds[r["case_id"]] = r["adjudication"].strip().upper()

    bucket_stats = collections.defaultdict(lambda: [0, 0])  # bucket -> [n, correct]
    rule_stats = collections.defaultdict(lambda: [0, 0])
    total = [0, 0]
    for line in open(args.features):
        f = json.loads(line)
        cid = f["case_id"]
        if cid not in truth or cid not in preds:
            continue
        ok = int(preds[cid] == truth[cid])
        b = bucket_of(f)
        bucket_stats[b][0] += 1
        bucket_stats[b][1] += ok
        rule_stats[f["rule"]][0] += 1
        rule_stats[f["rule"]][1] += ok
        total[0] += 1
        total[1] += ok

    global_acc = total[1] / max(total[0], 1)
    table = {}
    K = 8  # smoothing pseudo-count toward the rule-level rate
    for b, (n, c) in sorted(bucket_stats.items()):
        rn, rc = rule_stats[b[0]]
        rule_acc = rc / max(rn, 1)
        acc = (c + K * rule_acc) / (n + K)
        table["|".join(b)] = round(min(max(acc, 0.02), 0.99), 3)
    rules = {r: round(min(max(c / max(n, 1), 0.02), 0.99), 3) for r, (n, c) in rule_stats.items()}

    with open(args.out, "w") as f:
        f.write('"""Confidence calibration table fit on the public training set.\n')
        f.write("Generated by tools/fit_calibration.py — do not edit by hand.\"\"\"\n\n")
        f.write(f"GLOBAL_ACC = {round(global_acc, 3)}\n\n")
        f.write(f"RULE_ACC = {json.dumps(rules, indent=1, sort_keys=True)}\n\n")
        f.write(f"BUCKET_ACC = {json.dumps(table, indent=1, sort_keys=True)}\n\n")
        f.write('''

def _band_ocr(min_conf):
    if min_conf is None:
        return "text"
    if min_conf >= 60:
        return "hi"
    if min_conf >= 45:
        return "mid"
    return "lo"


def lookup(features):
    rule = features.get("rule", "?")
    ocr = _band_ocr(features.get("min_ocr_conf"))
    miss = features.get("missing_fields", 0)
    miss = "0" if miss == 0 else ("1" if miss == 1 else "2+")
    key = f"{rule}|{ocr}|{miss}"
    if key in BUCKET_ACC:
        return BUCKET_ACC[key]
    if rule in RULE_ACC:
        return RULE_ACC[rule]
    return GLOBAL_ACC
''')
    print(f"wrote {args.out}: {len(table)} buckets, {len(rules)} rules, global={global_acc:.3f}")

    # Diagnostic: rule-level truth distribution for decision-policy review.
    dist = collections.defaultdict(collections.Counter)
    for line in open(args.features):
        f = json.loads(line)
        cid = f["case_id"]
        if cid in truth:
            dist[f["rule"]][truth[cid]] += 1
    print("\nrule -> truth distribution:")
    for r, c in sorted(dist.items()):
        print(f"  {r:22s} {dict(c)}")


if __name__ == "__main__":
    main()
